### ISSUE TITLE
Index value update is deleting all the indexes rather than deleting the index with old value

### ISSUE THREAD

**Issue by sujatha-mh** [egraphdb/egraphdb#2]
Consider a case where below given are the current indexes. (some text based index)

| Index Value | Id    |
|-------------|-------|
| "xyz"       | "123" |
| "xyz"| "234"|
|"xyz"| "345"|

On request to update index value to "abc" for Id "234",

- deletes all the entry with "xyz" index value
- creates index "abc" for Id "234.

Resulting table :

| Index Value | Id    |
|-------------|-------|
| "abc"       | "234" |

Ideally it should only delete index with old value and create new entry or update index value with new value

Expected:

| Index Value | Id    |
|-------------|-------|
| "xyz"       | "123" |
| "abc"| "234"|
|"xyz"| "345"|

**Comment by neeraj9** [comment]
This is actually true. Somehow the index deletion logic did not account for specific entry deletion hence the bug. Thanks @sujatha-mh for finding this bug and proposing a fix.
